- id: 0d3714f8-5d98-4791-a7b1-3457275b66d7
  name: Frederic Jast
  email: junita.russel@gmail.com
  userType: REGULAR
- id: 1c7d22b4-d71d-4467-a737-072d78e2eedc
  name: Suk Bruen
  email: corie.ritchie@yahoo.com
  userType: PREMIUM
- id: 41548bf4-8431-4dbb-9c74-881d69b0a89c
  name: Del Kessler V
  email: hedwig.dibbert@gmail.com
  userType: REGULAR
- id: c1a53b5b-5d36-4041-96e4-919f539adfb7
  name: Mark Lehner
  email: kenneth.kozey@gmail.com
  userType: PREMIUM
- id: d7d16d99-4dcb-4526-8609-9c9a1cab646e
  name: Jeraldine Brown
  email: zachary.schaefer@hotmail.com
  userType: PREMIUM
- id: 8e27fbc7-0766-4e76-854a-273b81542bd7
  name: Mrs. Dian Walsh
  email: vernon.beatty@hotmail.com
  userType: REGULAR
- id: 813d2281-dc4a-4ce9-84f3-ceea70da6ba0
  name: Michel Lowe
  email: antonia.ledner@gmail.com
  userType: REGULAR
- id: 04af3d79-12bc-44ea-9c21-6b0a6adf8cd0
  name: Roma Hyatt
  email: lakisha.pouros@yahoo.com
  userType: PREMIUM
- id: c9b971ca-dc93-42fe-b14f-c39f9c6b6b11
  name: Henry Braun
  email: robbie.altenwerth@yahoo.com
  userType: PREMIUM
- id: be7fe6ca-f9a2-43a2-95e4-abd949eb13d3
  name: Manual Runolfsson
  email: carlo.huel@gmail.com
  userType: REGULAR
